### ISSUE TITLE
cred相关api失效

### ISSUE THREAD

**Issue by sakaiyuuji4** [ProbiusOfficial/Skland_API#1]
目前cred相关的api调用时返回“签名验证失败”

**Comment by ProbiusOfficial** [comment]
原因已经查明为追加了签名校验过程，目前的解决方法是模拟旧APP的签到head。
正在研究签名的生成过程，疑似使用js计算而成，但js (skland/site/index.333768.js) 似乎存在混淆加密。
其他使用Cred 如获取游戏状态的API 目前工作正常

**Comment by yawwwwwn** [comment]
哪个旧header能用啊？能不能给抄一下让代码先苟住（。

**Comment by sakaiyuuji4** [comment]
> 哪个旧header能用啊？能不能给抄一下让代码先苟住（。

'User-Agent': 'Skland/1.0.1 (com.hypergryph.skland; build\': \'100001014; Android 31; ) Okhttp/4.11.0',
                    'vCode': '100001014',
                    'vName': '1.0.1',
                    'dId': 'de9759a5afaa634f',
                    'platform': '1'
                    我现在用的是这个

**Comment by xxyz30** [comment]
> 哪个旧header能用啊？能不能给抄一下让代码先苟住（。

https://gitee.com/FancyCabbage/skyland-auto-sign#sign-header
参数验证实现

**Comment by ProbiusOfficial** [comment]
已有对应解决方法，参考https://gitee.com/FancyCabbage/skyland-auto-sign#sign-header
基于不重复造轮子原则，项目会在不久后（指补考完）参考更新对应api部分，感谢@xxyz30 提供解决方法。
